Feature/create remedy
Rahaf91/capstone-natural-cures pull request #12
Opened 2024-08-15 10:11 UTC by Rahaf91

2024-08-19 11:26 UTC, P-Oliomonte requested changes
Just some advice and the change we discussed during checkout. 

All in all well done :-)

2024-08-19 11:26 UTC, P-Oliomonte commented on components/RemedyForm.js
> +            </button>
```suggestion
            {ingredients.length > 1 && (<button type="button"
              onClick={() => handleRemoveIngredients(index)}
            >
              🗑️
            </button>)}
```

2024-08-19 11:26 UTC, P-Oliomonte commented on components/RemedyForm.js
> +            <option key={index} value={symptom}>
Like above, the key could be more specific like "symptom"

2024-08-19 11:26 UTC, P-Oliomonte commented on components/RemedyForm.js
> +          <div key={index}>
Like above, the key could be more specific like "selectedSymptom"

2024-08-19 12:45 UTC, Rahaf91 commented on components/RemedyForm.js
> +          <div key={index}>
Yes sure both are okay, name  is better when the list is subject to changes (update lists)

2024-08-19 12:48 UTC, Rahaf91 commented on components/RemedyForm.js
> +        <label>
I think for accessibility we should use label  when we dealing with form ..But yes we are dealing with multiple fields of ingredients which all share the same label .. so yes for better accessibility, I think we should here define a unique id for each ingredient input and use htmlFor:) so all inputs  share the same name but different id(s)

2024-08-19 12:53 UTC, Rahaf91 commented on components/RemedyForm.js
> +            <input
I did not have that error ,,anyway see my answer at your comment on label

2024-08-19 13:48 UTC, Rahaf91 commented
Thank you 😊

2024-08-20 09:39 UTC, JessicaLoers approved these changes
**Well done, Team ✨**

I have a few suggestions for you, particularly regarding accessibility. I recommend creating a more comprehensive user story that addresses all accessibility improvements. 

_For now, the PR is approved._

2024-08-20 09:39 UTC, JessicaLoers commented on components/RemedyForm.js
> +    };
**Recommendation:** Consider using `Object.fromEntries(formData)` to convert the FormData object into a plain javascript object. This approach is what we learned in the bootcamp and can make it easier to manage form data, especially when dealing with multiple fields. 
_However, the current use of `formData.get()` is also perfectly valid and not wrong._

2024-08-20 09:39 UTC, JessicaLoers commented on components/RemedyForm.js
> +          Ingredients:<span aria-label="required">*</span>
**Not so funny fun fact.**  😁
The aria-label isn't strictly necessary here because most screen readers can interpret the asterisk * as indicating a required field. However, there is a potential risk that the asterisk could be misinterpreted as a reference to a footnote instead. 🫨

To avoid any confusion and ensure clarity, you might consider using the aria-label to explicitly indicate that the field is required:

```js
<label htmlFor="ingredients-group" aria-label="Ingredients, required">
  Ingredients: <span>*</span>
</label>
```

You can also just leave it as is for now and plan to write a more comprehensive user story addressing all accessibility checks and improvements later on during the Capstone phase.

2024-08-20 09:39 UTC, JessicaLoers commented on components/RemedyForm.js
> +            )}
It is advisable to wrap icons in a span element and use an aria-label to make the button's purpose clear to screen reader users.

```suggestion
             <button type="button" onClick={() => handleRemoveIngredients(index)}>
           <span aria-label="Remove ingredient">🗑️</span>
           </button>
            )}
```

2024-08-20 09:39 UTC, JessicaLoers commented on components/RemedyForm.js
> +        <button type="button" onClick={handleAddIngredients}>
In this case, you can omit the span element since it doesn't serve a specific purpose.

Whether or not to use a `<span>` around an icon or symbol like an emoji or a + sign depends on the context and how you want to handle accessibility.

**Another fun fact**
Emojis like 🗑️ are visual symbols that may not convey clear meaning by themselves, especially for screen reader users. Wrapping an emoji in a `<span>` with an aria-label allows you to describe the emoji’s purpose more explicitly (e.g., "Remove ingredient"). This is particularly important when the emoji is used as the primary indicator of the button's function.

A + sign is a more conventional symbol in interfaces, often recognised as "add" or "expand" without additional context. However, if you want to ensure consistency and accessibility, you could treat it similarly to the emoji.


Example:
```js
// For the Remove button
<button type="button" onClick={() => handleRemoveIngredients(index)}>
  <span aria-label="Remove ingredient">🗑️</span>
</button>

// For the Add button
<button type="button" onClick={handleAddIngredients}>
  <span aria-label="Add ingredient">+</span>
</button>
```

> 💡 As previously mentioned, you’re welcome to take note of these suggestions and save them for a more comprehensive accessibility user story later on.

2024-08-20 09:39 UTC, JessicaLoers commented on components/RemedyForm.js
> +  cursor: pointer;
For a standard `<button>` element, `cursor: pointer`; isn't necessary because it's applied by default.
However, adding it doesn't hurt and can clarify intent or ensure consistency across different elements.

2024-08-20 10:42 UTC, merged