Feature/delete remedy
Rahaf91/capstone-natural-cures pull request #14
Opened 2024-08-21 09:55 UTC by AbdulrahmanTabbakh

2024-08-21 13:05 UTC, JessicaLoers requested changes
**Great work on the project so far! ✨** 

I have a few suggestions that could enhance the clarity, reusability, and maintainability of your code. 

Furthermore consider modify and renaming the  component  `ModalDelete.js` to something more generic, like `ConfirmationDialog`. To make the component more reusable across different parts of your application, as it won’t be tied to a specific context (like deleting a remedy).  **_This could also be a task for refactoring in the future._**

2024-08-22 07:20 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  };
function handleConfirmDelete() {
  setShowModal(false);
  onDelete();
}

2024-08-22 07:33 UTC, SylvieDoumet commented on components/ModalDelete.js
> +            <CloseButton onClick={handleCloseModal}>&times;</CloseButton>
The stopPropagation function is prevents the click event on the modal content from triggering the click event on the modal's background, which would close the modal. However, we can throw it out here if considered : 

{showModal && (
  <Modal onClick={handleCloseModal}>
    <ModalContent></ModalContent>
     </Modal>
     )}

2024-08-22 07:35 UTC, SylvieDoumet commented on components/ModalDelete.js
> +          <ModalContent onClick={(e) => e.stopPropagation()}>
The stopPropagation function is prevents the click event on the modal content from triggering the click event on the modal's background, which would close the modal. However, we can throw it out here if considered : 


```
{showModal && (
  <Modal onClick={handleCloseModal}>
    <ModalContent></ModalContent>
     </Modal>
     )}
```

2024-08-22 07:38 UTC, SylvieDoumet commented on components/ModalDelete.js
> +            <CloseButton onClick={handleCloseModal}>&times;</CloseButton>
Updated code according to considerations

```
{showModal && (
  <Modal>
    <ModalContent>
      <button onClick={handleConfirmDelete}>Delete</button>
      <button onClick={toggleModal}>Cancel</button>
    </ModalContent>
  </Modal>
)}
```

2024-08-22 07:39 UTC, SylvieDoumet commented on components/ModalDelete.js
> +              <h1>Delete Remedy</h1>
<Container>
              <h2>Delete Remedy</h2>

2024-08-22 07:40 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  cursor: pointer;
deletion of L. 94

2024-08-22 07:44 UTC, SylvieDoumet commented on pages/remedy/[id].js
> +  }
Insert consideration : 

```
 function deleteRemedyAndRedirect(id) {
    handleDeleteRemedy(id);
    router.push("/");
  }

```

2024-08-22 07:49 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  }
Change .close-button 

From : 
```
const CloseButton = styled.span`
  position: absolute;
  right: 15px;
  top: 10px;
  font-size: 40px;
  font-weight: bold;
  color: #f8fbca;
  cursor: pointer;

  &:hover {
    color: #f44336;
  }
`;
```

To

2024-08-22 07:54 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  }
Change close button 

From : 

```
const DeleteButton = styled.button`
  background-color: #54582f;
  color: #f8fbca;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
  opacity: 0.9;

  &:hover {
    opacity: 1;
  }
`;
```

To :

2024-08-22 07:54 UTC, SylvieDoumet commented on components/ModalDelete.js
> +            <CloseButton onClick={handleCloseModal}>&times;</CloseButton>
Delete close-button 

```
const CloseButton = styled.span`
  position: absolute;
  right: 15px;
  top: 10px;
  font-size: 40px;
  font-weight: bold;
  color: #f8fbca;
  cursor: pointer;

  &:hover {
    color: #f44336;
  }
`;
```

2024-08-22 07:57 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  cursor: pointer;
deletion of L.112

2024-08-22 08:01 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  }
```
.close-button 
....
....
opacity: 0.8;
transition: opacity 0.3s ease, transform 0.2s ease;

.close-button:active,
.close-button:focus {
  opacity: 1;
  transform: scale(1.1);
}
```
The :active and :focus states provide visual feedback when the button is tapped or focused on. This includes setting opacity: 1 and slightly scaling up the button using transform: scale(1.1) to give a tactile feel.The transition property ensures that the changes in opacity and scale happen smoothly, providing a better user experience.

2024-08-22 08:46 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  font-size: 40px;
Suggestion : 
A CSS variable `theme `can be defined to ensure consistency across the application. The variable can be used for font sizes, font weights, colors, padding, margins, and button width. 

```
const theme = {
  fontSizeLarge: '2.5rem', // Equivalent to 40px if base font size is 16px
  fontSizeMedium: '1rem', // Equivalent to 16px
  fontWeightBold: '700',
  colorPrimary: '#f8fbca', // Background color for modal content
  colorAccent: '#54582f',  // Border color
  colorHover: '#f44336',   // Example hover color for CloseButton
  colorButtonBackground: '#86895d', // Background color for CancelButton
  colorButtonConfirm: '#bec092',    // Background color for ConfirmDeleteButton
  colorButtonText: '#54582f',       // Text color for buttons
  paddingSmall: '1rem', // Equivalent to 16px
  paddingMedium: '0.875rem', // Equivalent to 14px
  marginSmall: '0.5rem', // Equivalent to 8px
  widthButton: '48%',
};
```

**Relative Units** 
We can replace the pixel values with `rem` to improve scalability and responsiveness. For example, 40px is converted to 2.5rem, assuming a base font size of 16px.
```

const Modal = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  position: fixed;
  z-index: 1;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(84, 88, 47, 0.9); // Same as colorAccent
`;

const ModalContent = styled.div`
  background-color: ${theme.colorPrimary}; // #f8fbca
  margin: auto;
  border: 1px solid ${theme.colorAccent}; // #54582f
  width: 80%;
  max-width: 31.25rem; /* Equivalent to 500px if base font size is 16px */
  padding: ${theme.paddingSmall};
  position: relative;
  text-align: center;
`;

const Container = styled.div`
  padding: ${theme.paddingSmall};
  text-align: center;
`;

const CloseButton = styled.span`
  position: absolute;
  right: 0.9375rem; /* Equivalent to 15px if base font size is 16px */
  top: 0.625rem; /* Equivalent to 10px if base font size is 16px */
  font-size: ${theme.fontSizeLarge};
  font-weight: ${theme.fontWeightBold};
  color: ${theme.colorPrimary}; // #f8fbca
  cursor: pointer;

  &:hover {
    color: ${theme.colorHover}; // Color for hover effect
  }
`;

const ButtonGroup = styled.div`
  display: flex;
  justify-content: space-between;
`;

const CancelButton = styled.button`
  background-color: ${theme.colorButtonBackground}; // #86895d
  color: ${theme.colorButtonText}; // #54582f
  padding: ${theme.paddingMedium};
  margin: ${theme.marginSmall} 0;
  border: none;
  cursor: pointer;
  width: ${theme.widthButton};

  &:hover {
    opacity: 0.8;
  }
`;

const ConfirmDeleteButton = styled.button`
  background-color: ${theme.colorButtonConfirm}; // #bec092
  color: ${theme.colorButtonText}; // #54582f
  padding: ${theme.paddingMedium};
  margin: ${theme.marginSmall} 0;
  border: none;
  cursor: pointer;
  width: ${theme.widthButton};

  &:hover {
    opacity: 0.8;
  }
`;
```

2024-08-22 08:48 UTC, SylvieDoumet commented on components/ModalDelete.js
> +  font-size: 40px;
The 
&:hover {
    opacity: 0.8;
  }

Is just an add on that could be left in for desktop applications - for the version mobile first I can be left out

2024-08-22 19:36 UTC, JessicaLoers approved these changes
**Hi Team ✨**

I've noticed another pattern in the code that don't align with the learned practices and conventions from the Bootcamp curriculum. 

Please ensure that you stick to the writing styles and conventions we've been taught. Exceptions are always possible, but they should be justified accordingly.

Given that the Public Sprint Review is just around the corner and I completely understand that you'd like to present this feature, I will approve the PR. 

**_However, I trust that you'll incorporate my feedback accordingly._** 😇

2024-08-22 19:36 UTC, JessicaLoers commented on components/ModalDelete.js
> +      <DeleteButton onClick={() => toggleModal()}>Delete Remedy</DeleteButton>
You don't need to explicitly use a callback function if you pass the function as a reference

```suggestion
      <DeleteButton onClick={toggleModal}>Delete Remedy</DeleteButton>
```

2024-08-22 19:36 UTC, JessicaLoers commented on components/ModalDelete.js
> +  }
I wanted to mention that while using the `function` keyword in the `toggleModal` function is not incorrect, the following approach is more common and aligns with what we learned in the bootcamp.

⚠️ Unless you can provide us with a super valid reason for using the `function` keyword, please make sure to adhere to the conventions outlined in our curriculum.

```suggestion
 function toggleModal() {
  setShowModal((prevShowModal) => !prevShowModal);
}
```

2024-08-22 19:36 UTC, JessicaLoers commented on components/ModalDelete.js
> +            <button onClick={() => toggleModal()}>Cancel</button>
Same as above: You don't need to explicitly use a callback function if you pass the function as a reference

2024-08-22 19:46 UTC, JessicaLoers commented on components/ModalDelete.js
> +  };
@SylvieDoumet 

There’s no need to add the changes here as comments — if you make these suggestions in the codebase, they will be visible in the updated PR.  

Also, I’m not able to review code that isn’t highlighted anyway.  😁

2024-08-22 19:56 UTC, Rahaf91 commented
Thank you, Jessica, for taking the time to review the code. I have updated it now. :)

2024-08-23 07:15 UTC, merged