Feature/uniform design
Rahaf91/capstone-natural-cures pull request #28
Opened 2024-09-04 07:35 UTC by Rahaf91

2024-09-05 15:12 UTC, anapecic requested changes
Hey guys, looking promising already! We are not sure how far you wanted to design this through (especially in comparison with your examples in the US) which makes it hard to feedback the design in general. This might be something to add to future user stories. 

One thing that kept popping up is the use of custom props instead of extending styles. Here is the docu by styled components about this topic and I also left some comments in between. Maybe consult the coaches about this, since this would probably mean more major changes. https://styled-components.com/docs/basics#extending-styles

In general there is the question of how consistent you want to be in using sizes and units. Sometimes you are using pixels for margins, sometimes rems and so on. This might be a conscious decision on your part, so this is just optional feedback. 

We like that you are using variables in the global styles - makes everything more consistent :)

2024-09-05 15:12 UTC, anapecic commented on components/ModalDelete.js
> +        <StyledButton $variant="delete" onClick={toggleModal}>
You are using a custom prop to change the style of the buttons. Here it would make more sense to work with styled components and extend existing styled components. 

You can define a "BaseButton" and extend it with a different color. E.g.

```
const BaseButton = styled.button`
border: none;
  padding: 10px 20px;
  font-size: 1rem;
  border-radius: 5px;
  margin-top: 10px;
  transition: background-color 0.3s ease, transform 0.2s ease;
  text-align: center;
  text-decoration: none;
  display: inline-block;
`
//extend the styles based on the BaseButton
const CancelButton = styled(BaseButton)`
color: red;
`
```

2024-09-05 15:12 UTC, anapecic commented on components/StyledButtons.js
Same Feedback as before: Try to use extended styles instead of repeating code :)

2024-09-05 15:12 UTC, anapecic commented on components/StyledLinks.js
> +    props.$variant === "back" &&
same feedback as before :)

2024-09-06 06:22 UTC, Rahaf91 commented on components/Icons.js
> +    <FontAwesomeIcon icon={selectedIcon} color={color} size={size} {...props} />
Thank you ,Yes and that is why I defined here props so that, each icon receive additional attributes dynamically, such as aria-label which is defined separately in RemedyForm.

2024-09-06 06:23 UTC, Rahaf91 commented on components/FilterList.js
> +          <FilterOption value="">Filter by Symptom</FilterOption>
Since the value is an empty string, it won't be added,,but I will implement that

2024-09-06 06:26 UTC, Rahaf91 commented on components/RemediesList.js
> +  margin-bottom: 1rem;
Yes, I know because more than one person was working on it, and each had their own approach. We'll try to fix that in another user story.

2024-09-06 06:36 UTC, Rahaf91 reviewed
Thank you for taking the time to review

2024-09-06 06:39 UTC, Rahaf91 commented on components/FavoriteButton.js
>        aria-label={isFavorite ? "Unmark as favorite" : "Mark as Favorite"}
I’m not sure about this; I think it’s from another user story. I will ask.

2024-09-17 14:12 UTC, Inelukas reviewed
The new design looks great! Green tick from us 😉

2024-09-17 14:26 UTC, Rahaf91 commented
Thanks for your time and feedback, we really appreciate it..🙌

2024-09-18 09:14 UTC, merged