Feature/icons
Rahaf91/capstone-natural-cures pull request #73
Opened 2024-10-02 07:34 UTC by SylvieDoumet

2024-10-02 09:59 UTC, eneben requested changes
Moin allerseits :)
Wir haben ziemlich viel nicht richtig verstanden ehrlich gesagt. Was wir verstanden haben und wozu uns etwas aufgefallen ist, haben wir reingeschrieben. Das meiste bei den Kommentaren sind Kleinigkeiten. Uns ist aber beim Durchklicken der Vercel Preview einiges aufgefallen, was wir hier noch mal auflisten. Deshalb auch der graue Haken – spätestens bei der Quality Assurance würde das nicht durchgehen, vermuten wir. Ihr könnt ja mal schauen, was davon Ihr bei einer anderen US eh schon angeht oder was Euch egal ist und was Ihr noch ausbessern müsst. 
Das war aber auch eine echt große Refactoring-Story! Nicht den Mut verlieren! ;-) 
- Dieses Akzeptanzkriterium ist nicht erfüllt:
"If a category does not contain any remedies, a message should be displayed indicating that there are no available remedies for that health issue instead of an empty page."
- "View Bookmarked remedies"-Button auf Startseite überlappt (auf verschiedenen pages). Bei Desktopview verschiebt er sich nach rechts.
- am Design seid Ihr ja noch, oder? Die Desktopansicht sieht etwas wild aus und der Printbutton hat zB keine abgerundeten Ecken usw.
- Wir fänden sinnvoll das Logo zu einem Link zur Homepage zu machen mit categories "all" (das wäre auch sinnvoll in dieser Story)
- Der Back Button in Recipe führt nicht zurück zu vorheriger Seite, sondern zu Homepage. Aber: Der ausgewählte Körperbereich ist dann oben drüber als Icon auch auf der Homepage.
- Wenn ich den Zurück-Button benutze (oder beim Handy Zurück-Swipe), lädt die Startseite nicht, und da steht "...loading". In der URL steht noch die URL von davor.
- Aus der Suche keine Möglichkeit zurück zu gehen. Ich kann die Suche löschen, aber es gibt keinen Back-Button oder so.
- Ist es Absicht, dass das Suchfeld ausgefüllt bleibt, wenn ich in verschiedene Bereiche navigiere? Ich würde es zwischendurch resetten
- in der Console gibt es zwei Error meldungen. Wir glauben, es bezieht sich hierauf. Remedy Form Zeilen 130 ff.:
```
<Label htmlFor="ingredients-group" aria-label="Ingredients, required">
          Ingredients: <span>*</span>
        </Label>
        {ingredients.map((ingredient, index) => (
          <InputGroup key={index}>
            <Input
              id={`ingredient-${index}`}
              ```
(siehe Screenshot)
- Daily Health Tips: sind an Größe des Bildes angepasst, daher springt die Größe von Tipp zu Tipp bei Desktopansicht
- Detailansicht von Rezepten ist noch sehr schmal und die Bilder sind darin gestaucht
- margin/padding/gap...: rem nicht sinnvoll, lieber px. rem ist gut für Schriftgrößen zB. Wenn jemand zB schlechte Augen hat und die default-font-size sehr groß ist, sollten sich nicht die Abstände sehr vergrößern, sondern es sollte noch möglichst viel Content der Page zu sehen sein. 

Das ist, was uns so aufgefallen ist. Wir hoffen, damit könnt Ihr was anfangen. Alles gehört vermutlich nicht zu dieser US, aber so Sachen wie der Zurück-Button oder so sollten schon funktionieren und das eine Akzeptanzkriterium ist halt nicht erfüllt. Guten Mut weiterhin und viel Spaß ! :blush:

2024-10-02 09:59 UTC, eneben commented on components/RemedyForm.js
> +// +
Die Kommentare sollten wir immer alle rauslöschen... (ich schreib das jetzt nicht für jeden ^^)

2024-10-02 09:59 UTC, eneben commented on components/RemedyForm.js
>      router.back();
Nur als Idee: Wir fänden sinnvoll, wenn man nach Submit in der Kategorie von dem Rezept landet, was man eingegeben hat, damit man sehen kann, ob die Eingabe funktioniert hat.

2024-10-02 09:59 UTC, eneben commented on components/RemedyForm.js
> +          <option value="" hidden>
Was macht hidden hier? :)

2024-10-02 09:59 UTC, eneben commented on components/Subheader.js
> +  if (!selectedCategory) return null;
Der Back Button in Recipe führt nicht zurück zu vorheriger Seite, sondern zur Homepage. Aber: Der ausgewählte Körperbereich ist dann oben drüber als Icon auch auf der Homepage. Vermutlich müsstet Ihr da die selectedCategory zurücksetzen?

2024-10-02 09:59 UTC, eneben commented on components/Subheader.js
> +  padding: 0, 5rem;
Das Komma kann weg. ;)

```suggestion
  padding: 0 5rem;
```

2024-10-02 09:59 UTC, eneben commented on pages/_app.js
>      const regex = new RegExp(`\\b${query}`, "i");
Nur weil ich es nciht verstehe: Warum macht Ihr das? :D

2024-10-02 09:59 UTC, eneben commented on pages/_app.js
> +        : Array.from(
Hier habt Ihr eine Codewiederholung. Das gleiche macht Ihr ja oben schon bei allSymptoms, oder?
Gerade wird bei der Auswahl von "all" jedes Mal ein neues Array mit allen Symptomen erstellt. Die Neuberechnungen könntet ihr vielleicht so vermeiden:

`const selectedSymptoms = value !== "all" ? [value] : allSymptoms;`

2024-10-02 09:59 UTC, eneben commented on pages/index.js
> +  const [showDailyHealthTips, setShowDailyHealthTips] = useState(true);
Diese States könntet Ihr vielleicht zusammenfassen in einem State, der zB 
`const [pageMode, setPageMode] = useState("home")` 
heißt und dann könntet Ihr je nach Ansicht den String ändern zu `"category"` oder so. Dann müsstet Ihr nicht ganz so viel hin- und hertogglen. zB die `DailyHealthTips` würden in der `"home"` immer angezeigt und in der `"category"` nicht.

2024-10-02 09:59 UTC, eneben commented on pages/index.js
> +    setShowDailyHealthTips(false);
s.o., ein anderes State-Management würde es vereinfachen...

2024-10-02 09:59 UTC, eneben commented on pages/index.js
> +    setShowDailyHealthTips(true);
s.o.

2024-10-02 09:59 UTC, eneben commented on pages/index.js
> +    // D
Kommentare löschen ;-)

2024-10-02 09:59 UTC, eneben commented on pages/index.js
> +    console.log("selectedSymptoms", selectedSymptoms),
console.log entfernen ;)

2024-10-04 08:03 UTC, NikRoe commented on pages/index.js
> +  const [showDailyHealthTips, setShowDailyHealthTips] = useState(true);
Hi zusammen,

ich habe gerade mit der Gruppe zusammengesessen und vereinbart, dass das State-Handling an dieser Stelle zunächst nicht weiter angepasst werden muss, auch wenn der Vorschlag ein sehr guter ist!

2024-10-04 08:55 UTC, SylvieDoumet commented on components/RemedyForm.js
>      router.back();
Kommentare wurden alle von uns entfernt

2024-10-04 08:55 UTC, SylvieDoumet commented on pages/index.js
> +    setShowDailyHealthTips(false);
s.o.

2024-10-04 08:55 UTC, SylvieDoumet commented on pages/index.js
> +    setShowDailyHealthTips(true);
s.o.

2024-10-04 08:56 UTC, SylvieDoumet commented on pages/index.js
> +    console.log("selectedSymptoms", selectedSymptoms),
console.logs wurden entfernt

2024-10-04 09:46 UTC, SylvieDoumet commented
> Moin allerseits :) Wir haben ziemlich viel nicht richtig verstanden ehrlich gesagt. Was wir verstanden haben und wozu uns etwas aufgefallen ist, haben wir reingeschrieben. Das meiste bei den Kommentaren sind Kleinigkeiten. Uns ist aber beim Durchklicken der Vercel Preview einiges aufgefallen, was wir hier noch mal auflisten. Deshalb auch der graue Haken – spätestens bei der Quality Assurance würde das nicht durchgehen, vermuten wir. Ihr könnt ja mal schauen, was davon Ihr bei einer anderen US eh schon angeht oder was Euch egal ist und was Ihr noch ausbessern müsst. Das war aber auch eine echt große Refactoring-Story! Nicht den Mut verlieren! ;-)
> 
>     * Dieses Akzeptanzkriterium ist nicht erfüllt:
>       "If a category does not contain any remedies, a message should be displayed indicating that there are no available remedies for that health issue instead of an empty page."
> 
>     * "View Bookmarked remedies"-Button auf Startseite überlappt (auf verschiedenen pages). Bei Desktopview verschiebt er sich nach rechts.
> 
>     * am Design seid Ihr ja noch, oder? Die Desktopansicht sieht etwas wild aus und der Printbutton hat zB keine abgerundeten Ecken usw.
> 
>     * Wir fänden sinnvoll das Logo zu einem Link zur Homepage zu machen mit categories "all" (das wäre auch sinnvoll in dieser Story)
> 
>     * Der Back Button in Recipe führt nicht zurück zu vorheriger Seite, sondern zu Homepage. Aber: Der ausgewählte Körperbereich ist dann oben drüber als Icon auch auf der Homepage.
> 
>     * Wenn ich den Zurück-Button benutze (oder beim Handy Zurück-Swipe), lädt die Startseite nicht, und da steht "...loading". In der URL steht noch die URL von davor.
> 
>     * Aus der Suche keine Möglichkeit zurück zu gehen. Ich kann die Suche löschen, aber es gibt keinen Back-Button oder so.
> 
>     * Ist es Absicht, dass das Suchfeld ausgefüllt bleibt, wenn ich in verschiedene Bereiche navigiere? Ich würde es zwischendurch resetten
> 
>     * in der Console gibt es zwei Error meldungen. Wir glauben, es bezieht sich hierauf. Remedy Form Zeilen 130 ff.:
> 
> 
> ```
> <Label htmlFor="ingredients-group" aria-label="Ingredients, required">
>           Ingredients: <span>*</span>
>         </Label>
>         {ingredients.map((ingredient, index) => (
>           <InputGroup key={index}>
>             <Input
>               id={`ingredient-${index}`}
>               ```
> (siehe Screenshot)
> - Daily Health Tips: sind an Größe des Bildes angepasst, daher springt die Größe von Tipp zu Tipp bei Desktopansicht
> - Detailansicht von Rezepten ist noch sehr schmal und die Bilder sind darin gestaucht
> - margin/padding/gap...: rem nicht sinnvoll, lieber px. rem ist gut für Schriftgrößen zB. Wenn jemand zB schlechte Augen hat und die default-font-size sehr groß ist, sollten sich nicht die Abstände sehr vergrößern, sondern es sollte noch möglichst viel Content der Page zu sehen sein. 
> 
> Das ist, was uns so aufgefallen ist. Wir hoffen, damit könnt Ihr was anfangen. Alles gehört vermutlich nicht zu dieser US, aber so Sachen wie der Zurück-Button oder so sollten schon funktionieren und das eine Akzeptanzkriterium ist halt nicht erfüllt. Guten Mut weiterhin und viel Spaß ! :blush:
> ```

Wir haben eure Anmerkungen zum Styling in eine nachfolgende UserStory implementiert. Für die bei euch erschienene Error-message haben wir den Fehler behoben. 

Behobene Dinge sind : 

- Herauslöschen von console logs / Kommentaren 

- Hinzufügen von ll. 7-9 RemediesList.js / Update Message indicating that there are no available remedies for that health issue i

- Hinzufügen von l.43 index.js / Leeren der Searchbar bei Seitenwechsel 

- Löschen von l.239 RemedyForm.js / Behebung der Fehlermeldung verursacht durch initalen Wert {selectedCategory} - Herauslöschen des value

2024-10-17 09:16 UTC, closed without merging