feature/backend
Rahaf91/capstone-natural-cures pull request #75
Opened 2024-10-10 09:38 UTC by Rahaf91

2024-10-11 09:00 UTC, F-Kirchhoff requested changes
Hey Natural Cures Team,
your code looks very good already, well done! In some cases it might actually be overengineered for your given situation. Keep in mind to "keep it simple" whenever possible. There is an open question for me regarding your notes. You are using the _id in your frontend, but your notes don't have those defined in your schema.

2024-10-11 09:25 UTC, Rahaf91 commented on db/models/Remedy.js
> +  ],
Yes, right anyway we will change it in the personalized date user sotry

2024-10-11 10:28 UTC, Rahaf91 commented
Thanks for reviewing! As for the notes, we initially assumed that MongoDB would automatically generate an _id for each note since it's part of an array within the document. Given that MongoDB typically generates unique _ids for documents, we thought the same would apply to array elements without needing to explicitly define the _id field in the schema.

2024-10-11 13:48 UTC, F-Kirchhoff requested changes
Hey Rahaf,
I added an explainer why the _ids are not there. Please create unique ids manually for your notes in the notes array.

2024-10-11 13:48 UTC, F-Kirchhoff commented on components/Notes.js
> +          <NoteItem key={note._id}>
it only does this if the elements are documents in the collection, means that nested elements inside your remedy documents don't get _ids. You need to generate them by yourself.

2024-10-11 14:20 UTC, Rahaf91 commented
Sorry, maybe I didn't get your point, but when I look at the database, there is an _id for each note.
![IMG_20241011_161539](https://github.com/user-attachments/assets/6012bb15-b278-4543-995f-581308b10324)

2024-10-11 14:30 UTC, F-Kirchhoff commented
ok I am sorry, I was not aware of this behavior, apparently when you use the $push functionality from mongoose these are created. Then your pr is good to go.

2024-10-11 14:45 UTC, F-Kirchhoff commented on pages/api/remedies/[id]/notes/[noteId].js
> +  }
This part should not be under the url notes/[noteId].js but notes/index.js instead. If you create a new note there is no noteId yet to call.

2024-10-14 07:57 UTC, F-Kirchhoff approved these changes
LGTM, you can proceed to QA 🚀

2024-10-14 09:51 UTC, merged